### ISSUE TITLE
Utility doesn't work in kubernetes

### ISSUE THREAD

**Issue by futurekill** [snyk-tech-services/jira-tickets-for-new-vulns#131]
Hi,

I created a docker image in order to run the utility in in one of our kubernetes clusters. The image builds just fine but when I try to run it in kubernetes I get the following:

```
2022/06/30 03:29:41 *** INFO *** Project ID not specified - listing all projects that match the following filers:  projectCriticality:
 projectEnvironment:
 projectLifecycle:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x8442d1]

goroutine 1 [running]:
main.makeSnykAPIRequest(0x93ef2d, 0x3, 0xc00002c230, 0x48, 0x7ffff3a54dc2, 0x24, 0x0, 0x0, 0x0, 0xc00002c200, ...)
	/home/circleci/project/snyk_utils.go:38 +0x441
main.getOrgProjects(0xc000024510, 0x24, 0x9489a2, 0x13, 0x7ffff3a54dc2, 0x24, 0x0, 0x0, 0xc000028eb8, 0x4, ...)
	/home/circleci/project/snyk.go:65 +0x1a7
main.getProjectsIds(0xc000024510, 0x24, 0x9489a2, 0x13, 0x7ffff3a54dc2, 0x24, 0x0, 0x0, 0xc000028eb8, 0x4, ...)
	/home/circleci/project/snyk.go:90 +0x1ac
main.main()
	/home/circleci/project/main.go:24 +0x104
```

Here's my Dockerfile

```
FROM alpine:3

ENV VERSION 1.29.0
WORKDIR /snyk
RUN wget -q https://github.com/snyk-tech-services/jira-tickets-for-new-vulns/releases/download/${VERSION}/snyk-jira-sync-linux
ENV PATH /snyk:$PATH
COPY jira.yaml /snyk/
COPY entrypoint.sh /snyk/
RUN apk add --no-cache libc6-compat gcompat su-exec && \
    chmod +x snyk-jira-sync-linux entrypoint.sh

ENTRYPOINT ["/snyk/entrypoint.sh"]
```

And my entrypoint.sh:

```
#!/bin/sh

if [[ -z $SNYK_API_TOKEN ]];then
    echo "SNYK_API_TOKEN variable required."
    exit 1
fi

su-exec nobody /snyk/snyk-jira-sync-linux --configFile=/snyk --token=${SNYK_API_TOKEN} --debug=${DEBUG:false}
```

Any help/insight you can provide would be welcome.

**Comment by futurekill** [comment]
I have a jira.yaml file that I include in the image as well but that's got some sensitive stuff in it. One you guys have should work just the same.

**Comment by lili2311** [comment]
@futurekill  I can't see an `--orgID=` parameter set. Please make sure this is set and try again? See https://github.com/snyk-tech-services/jira-tickets-for-new-vulns#usage---quick-start

**Comment by futurekill** [comment]
All necessary parameters are set in my jira.yaml file. The same config works (though I sporadically get API errors) on my MacBook.

**Comment by lili2311** [comment]
@futurekill thanks for confirming, could you please set this env variable GODEBUG=http2debug=2 and try again?   This should show us which API call is causing this error hopefully.

**Comment by lili2311** [comment]
@futurekill did you manage to get this working?

**Comment by adnansakel** [comment]
I am also having the same issue. It does create some tickets on jira but after a while get this error. I am running the tool inside a docker container with an ubuntu base image. Following is the error message:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x844551]

goroutine 1 [running]:
main.makeSnykAPIRequest(0x93f3a7, 0x4, 0xc000270420, 0xa1, 0x7ffd5a50a8fa, 0x24, 0xc00016eb00, 0x2b2, 0x2c0, 0xc000135300, ...)
	/home/circleci/project/snyk_utils.go:38 +0x441
main.openJiraTicket(0x7ffd5a50a8cd, 0x24, 0x94899a, 0x13, 0x7ffd5a50a8fa, 0x24, 0x0, 0x0, 0x7ffd5a50a930, 0x4, ...)
	/home/circleci/project/jira.go:178 +0x6c4
main.openJiraTickets(0x7ffd5a50a8cd, 0x24, 0x94899a, 0x13, 0x7ffd5a50a8fa, 0x24, 0x0, 0x0, 0x7ffd5a50a930, 0x4, ...)
	/home/circleci/project/jira.go:235 +0x3c3
main.main()
	/home/circleci/project/main.go:80 +0xa50
```

**Comment by futurekill** [comment]
I apologize for not getting back to you. I think I'm all sorted out with this now. The latest version is working for me in a docker container.
